package iban

type Country struct {
	Name      string
	Code      string
	CharCount int
	Format    string
}

// Taken from https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country
var countries = map[string]Country{
	"AL": Country{
		Name:      "Albania",
		Code:      "AL",
		CharCount: 28,
		Format:    "ALkk bbbs sssx cccc cccc cccc cccc",
	},
	"AD": Country{
		Name:      "Andorra",
		Code:      "AD",
		CharCount: 24,
		Format:    "ADkk bbbb ssss cccc cccc cccc",
	},
	"AT": Country{
		Name:      "Austria",
		Code:      "AT",
		CharCount: 20,
		Format:    "ATkk bbbb bccc cccc cccc",
	},
	"AZ": Country{
		Name:      "Azerbaijan",
		Code:      "AZ",
		CharCount: 28,
		Format:    "AZkk bbbb cccc cccc cccc cccc cccc",
	},
	"BH": Country{
		Name:      "Bahrain",
		Code:      "BH",
		CharCount: 22,
		Format:    "BHkk bbbb cccc cccc cccc cc",
	},
	"BY": Country{
		Name:      "Belarus",
		Code:      "BY",
		CharCount: 28,
		Format:    "BYkk bbbb aaaa cccc cccc cccc cccc",
	},
	"BE": Country{
		Name:      "Belgium",
		Code:      "BE",
		CharCount: 16,
		Format:    "BEkk bbbc cccc ccxx",
	},
	"BA": Country{
		Name:      "Bosnia and Herzegovina",
		Code:      "BA",
		CharCount: 20,
		Format:    "BAkk bbbs sscc cccc ccxx",
	},
	"BR": Country{
		Name:      "Brazil",
		Code:      "BR",
		CharCount: 29,
		Format:    "BRkk bbbb bbbb ssss sccc cccc ccct n",
	},
	"BG": Country{
		Name:      "Bulgaria",
		Code:      "BG",
		CharCount: 22,
		Format:    "BGkk bbbb ssss ttcc cccc cc",
	},
	"CR": Country{
		Name:      "Costa Rica",
		Code:      "CR",
		CharCount: 22,
		Format:    "CRkk 0bbb cccc cccc cccc cc",
	},
	"HR": Country{
		Name:      "Croatia",
		Code:      "HR",
		CharCount: 21,
		Format:    "HRkk bbbb bbbc cccc cccc c",
	},
	"CY": Country{
		Name:      "Cyprus",
		Code:      "CY",
		CharCount: 28,
		Format:    "CYkk bbbs ssss cccc cccc cccc cccc",
	},
	"CZ": Country{
		Name:      "Czech Republic",
		Code:      "CZ",
		CharCount: 24,
		Format:    "CZkk bbbb ssss sscc cccc cccc",
	},
	"DK": Country{
		Name:      "Denmark",
		Code:      "DK",
		CharCount: 18,
		Format:    "DKkk bbbb cccc cccc cc",
	},
	"DO": Country{
		Name:      "Dominican Republic",
		Code:      "DO",
		CharCount: 28,
		Format:    "DOkk bbbb cccc cccc cccc cccc cccc",
	},
	"TL": Country{
		Name:      "East Timor",
		Code:      "TL",
		CharCount: 23,
		Format:    "TLkk bbbc cccc cccc cccc cxx",
	},
	"EE": Country{
		Name:      "Estonia",
		Code:      "EE",
		CharCount: 20,
		Format:    "EEkk bbss cccc cccc cccx",
	},
	"FO": Country{
		Name:      "Faroe Islands",
		Code:      "FO",
		CharCount: 18,
		Format:    "FOkk bbbb cccc cccc cx",
	},
	"FI": Country{
		Name:      "Finland",
		Code:      "FI",
		CharCount: 18,
		Format:    "FIkk bbbb bbcc cccc cx",
	},
	"FR": Country{
		Name:      "France",
		Code:      "FR",
		CharCount: 27,
		Format:    "FRkk bbbb bsss sscc cccc cccc cxx",
	},
	"GE": Country{
		Name:      "Georgia",
		Code:      "GE",
		CharCount: 22,
		Format:    "GEkk bbcc cccc cccc cccc cc",
	},
	"DE": Country{
		Name:      "Germany",
		Code:      "DE",
		CharCount: 22,
		Format:    "DEkk bbbb bbbb cccc cccc cc",
	},
	"GI": Country{
		Name:      "Gibraltar",
		Code:      "GI",
		CharCount: 23,
		Format:    "GIkk bbbb cccc cccc cccc ccc",
	},
	"GR": Country{
		Name:      "Greece",
		Code:      "GR",
		CharCount: 27,
		Format:    "GRkk bbbs sssc cccc cccc cccc ccc",
	},
	"GL": Country{
		Name:      "Greenland",
		Code:      "GL",
		CharCount: 18,
		Format:    "GLkk bbbb cccc cccc cc",
	},
	"GT": Country{
		Name:      "Guatemala",
		Code:      "GT",
		CharCount: 28,
		Format:    "GTkk bbbb mmtt cccc cccc cccc cccc",
	},
	"HU": Country{
		Name:      "Hungary",
		Code:      "HU",
		CharCount: 28,
		Format:    "HUkk bbbs sssx cccc cccc cccc cccx",
	},
	"IS": Country{
		Name:      "Iceland",
		Code:      "IS",
		CharCount: 26,
		Format:    "ISkk bbbb sscc cccc iiii iiii ii",
	},
	"IE": Country{
		Name:      "Ireland",
		Code:      "IE",
		CharCount: 22,
		Format:    "IEkk aaaa bbbb bbcc cccc cc",
	},
	"IL": Country{
		Name:      "Israel",
		Code:      "IL",
		CharCount: 23,
		Format:    "ILkk bbbn nncc cccc cccc ccc",
	},
	"IT": Country{
		Name:      "Italy",
		Code:      "IT",
		CharCount: 27,
		Format:    "ITkk xbbb bbss sssc cccc cccc ccc",
	},
	"JO": Country{
		Name:      "Jordan",
		Code:      "JO",
		CharCount: 30,
		Format:    "JOkk bbbb ssss cccc cccc cccc cccc cc",
	},
	"KZ": Country{
		Name:      "Kazakhstan",
		Code:      "KZ",
		CharCount: 20,
		Format:    "KZkk bbbc cccc cccc cccc",
	},
	"XK": Country{
		Name:      "Kosovo",
		Code:      "XK",
		CharCount: 20,
		Format:    "XKkk bbbb cccc cccc cccc",
	},
	"KW": Country{
		Name:      "Kuwait",
		Code:      "KW",
		CharCount: 30,
		Format:    "KWkk bbbb cccc cccc cccc cccc cccc cc",
	},
	"LV": Country{
		Name:      "Latvia",
		Code:      "LV",
		CharCount: 21,
		Format:    "LVkk bbbb cccc cccc cccc c",
	},
	"LB": Country{
		Name:      "Lebanon",
		Code:      "LB",
		CharCount: 28,
		Format:    "LBkk bbbb cccc cccc cccc cccc cccc",
	},
	"LI": Country{
		Name:      "Liechtenstein",
		Code:      "LI",
		CharCount: 21,
		Format:    "LIkk bbbb bccc cccc cccc c",
	},
	"LT": Country{
		Name:      "Lithuania",
		Code:      "LT",
		CharCount: 20,
		Format:    "LTkk bbbb bccc cccc cccc",
	},
	"LU": Country{
		Name:      "Luxembourg",
		Code:      "LU",
		CharCount: 20,
		Format:    "LUkk bbbc cccc cccc cccc",
	},
	"MK": Country{
		Name:      "Macedonia",
		Code:      "MK",
		CharCount: 19,
		Format:    "MKkk bbbc cccc cccc cxx",
	},
	"MT": Country{
		Name:      "Malta",
		Code:      "MT",
		CharCount: 31,
		Format:    "MTkk bbbb ssss sccc cccc cccc cccc ccc",
	},
	"MR": Country{
		Name:      "Mauritania",
		Code:      "MR",
		CharCount: 27,
		Format:    "MRkk bbbb bsss sscc cccc cccc cxx",
	},
	"MU": Country{
		Name:      "Mauritius",
		Code:      "MU",
		CharCount: 30,
		Format:    "MUkk bbbb bbss cccc cccc cccc 000m mm",
	},
	"MC": Country{
		Name:      "Monaco",
		Code:      "MC",
		CharCount: 27,
		Format:    "MCkk bbbb bsss sscc cccc cccc cxx",
	},
	"MD": Country{
		Name:      "Moldova",
		Code:      "MD",
		CharCount: 24,
		Format:    "MDkk bbcc cccc cccc cccc cccc",
	},
	"ME": Country{
		Name:      "Montenegro",
		Code:      "ME",
		CharCount: 22,
		Format:    "MEkk bbbc cccc cccc cccc xx",
	},
	"NL": Country{
		Name:      "Netherlands",
		Code:      "NL",
		CharCount: 18,
		Format:    "NLkk bbbb cccc cccc cc",
	},
	"NO": Country{
		Name:      "Norway",
		Code:      "NO",
		CharCount: 15,
		Format:    "NOkk bbbb cccc ccx",
	},
	"PK": Country{
		Name:      "Pakistan",
		Code:      "PK",
		CharCount: 24,
		Format:    "PKkk bbbb cccc cccc cccc cccc",
	},
	"PS": Country{
		Name:      "Palestinian territories",
		Code:      "PS",
		CharCount: 29,
		Format:    "PSkk bbbb xxxx xxxx xccc cccc cccc c",
	},
	"PL": Country{
		Name:      "Poland",
		Code:      "PL",
		CharCount: 28,
		Format:    "PLkk bbbs sssx cccc cccc cccc cccc",
	},
	"PT": Country{
		Name:      "Portugal",
		Code:      "PT",
		CharCount: 25,
		Format:    "PTkk bbbb ssss cccc cccc cccx x",
	},
	"QA": Country{
		Name:      "Qatar",
		Code:      "QA",
		CharCount: 29,
		Format:    "QAkk bbbb cccc cccc cccc cccc cccc c",
	},
	"RO": Country{
		Name:      "Romania",
		Code:      "RO",
		CharCount: 24,
		Format:    "ROkk bbbb cccc cccc cccc cccc",
	},
	"SM": Country{
		Name:      "San Marino",
		Code:      "SM",
		CharCount: 27,
		Format:    "SMkk xbbb bbss sssc cccc cccc ccc",
	},
	"SA": Country{
		Name:      "Saudi Arabia",
		Code:      "SA",
		CharCount: 24,
		Format:    "SAkk bbcc cccc cccc cccc cccc",
	},
	"RS": Country{
		Name:      "Serbia",
		Code:      "RS",
		CharCount: 22,
		Format:    "RSkk bbbc cccc cccc cccc xx",
	},
	"SK": Country{
		Name:      "Slovakia",
		Code:      "SK",
		CharCount: 24,
		Format:    "SKkk bbbb ssss sscc cccc cccc",
	},
	"SI": Country{
		Name:      "Slovenia",
		Code:      "SI",
		CharCount: 19,
		Format:    "SIkk bbss sccc cccc cxx",
	},
	"ES": Country{
		Name:      "Spain",
		Code:      "ES",
		CharCount: 24,
		Format:    "ESkk bbbb ssss xxcc cccc cccc",
	},
	"SE": Country{
		Name:      "Sweden",
		Code:      "SE",
		CharCount: 24,
		Format:    "SEkk bbbc cccc cccc cccc cccc",
	},
	"CH": Country{
		Name:      "Switzerland",
		Code:      "CH",
		CharCount: 21,
		Format:    "CHkk bbbb bccc cccc cccc c",
	},
	"TN": Country{
		Name:      "Tunisia",
		Code:      "TN",
		CharCount: 24,
		Format:    "TNkk bbss sccc cccc cccc cccc",
	},
	"TR": Country{
		Name:      "Turkey",
		Code:      "TR",
		CharCount: 26,
		Format:    "TRkk bbbb bxcc cccc cccc cccc cc",
	},
	"AE": Country{
		Name:      "United Arab Emirates",
		Code:      "AE",
		CharCount: 23,
		Format:    "AEkk bbbc cccc cccc cccc ccc",
	},
	"GB": Country{
		Name:      "United Kingdom",
		Code:      "GB",
		CharCount: 22,
		Format:    "GBkk bbbb ssss sscc cccc cc",
	},
	"VA": Country{
		Name:      "Vatican City",
		Code:      "VA",
		CharCount: 22,
		Format:    "VAkk bbbc cccc cccc cccc cc",
	},
	"VG": Country{
		Name:      "Virgin Islands, British",
		Code:      "VG",
		CharCount: 24,
		Format:    "VGkk bbbb cccc cccc cccc cccc",
	},
	// Special list from Nordea
	"DZ": Country{
		Name:      "Algeria",
		Code:      "DZ",
		CharCount: 24,
		Format:    "DZkk nnnn nnnn nnnn nnnn nnnn",
	},
	"AO": Country{
		Name:      "Angola",
		Code:      "AO",
		CharCount: 25,
		Format:    "AOkk nnnn nnnn nnnn nnnn nnnn n",
	},
	"BJ": Country{
		Name:      "Benin",
		Code:      "BJ",
		CharCount: 28,
		Format:    "BJkk annn nnnn nnnn nnnn nnnn nnnn",
	},
	"BF": Country{
		Name:      "Burkina Faso",
		Code:      "BF",
		CharCount: 28,
		Format:    "BFkk nnnn nnnn nnnn nnnn nnnn nnnn",
	},
	"BI": Country{
		Name:      "Burundi",
		Code:      "BI",
		CharCount: 16,
		Format:    "BIkk nnnn nnnn nnnn",
	},
	"CM": Country{
		Name:      "Cameroon",
		Code:      "CM",
		CharCount: 27,
		Format:    "CMkk nnnn nnnn nnnn nnnn nnnn nnn",
	},
	"CV": Country{
		Name:      "Cape Verde",
		Code:      "CV",
		CharCount: 25,
		Format:    "CVkk nnnn nnnn nnnn nnnn nnnn n",
	},
	"IR": Country{
		Name:      "Iran",
		Code:      "IR",
		CharCount: 26,
		Format:    "IRkk 0bb0 nnnn nnnn nnnn nnnn nn",
	},
	"CI": Country{
		Name:      "Ivory Coast",
		Code:      "CI",
		CharCount: 28,
		Format:    "CIkk annn nnnn nnnn nnnn nnnn nnnn",
	},
	"MG": Country{
		Name:      "Madagascar",
		Code:      "MG",
		CharCount: 27,
		Format:    "MGkk nnnn nnnn nnnn nnnn nnnn nnn",
	},
	"ML": Country{
		Name:      "Mali",
		Code:      "ML",
		CharCount: 28,
		Format:    "MLkk annn nnnn nnnn nnnn nnnn nnnn",
	},
	"MZ": Country{
		Name:      "Mozambique",
		Code:      "MZ",
		CharCount: 25,
		Format:    "MZkk nnnn nnnn nnnn nnnn nnnn n",
	},
	"SN": Country{
		Name:      "Senegal",
		Code:      "SN",
		CharCount: 28,
		Format:    "SNkk annn nnnn nnnn nnnn nnnn nnnn",
	},
	"UA": Country{
		Name:      "Ukraine",
		Code:      "UA",
		CharCount: 29,
		Format:    "UAkk bbbb bbcc cccc cccc cccc cccc c",
	},
}
